name: build pdf

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: build pdf and upload release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'
      - run: npm install
      - name: build pdf
        run: npm run build:pdf
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
      - name: create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref }} ./docs/README.pdf --title "Release ${{ github.ref }}" --notes "Release notes here" --target ${{ github.sha }}
      - name: upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref }} ./docs/README.pdf --clobber
